In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
print(arr.dtype)

int32


In [5]:
arr2 = np.array([1,2,3,4,5],dtype=np.int16)

In [6]:
arr2

array([1, 2, 3, 4, 5], dtype=int16)

Zero
ones
arange
random.rand
linspace

In [7]:
Z=np.zeros(5)

In [8]:
Z

array([0., 0., 0., 0., 0.])

In [9]:
ar=np.arange(0,10,1)

In [10]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ran=np.random.rand(4)

In [12]:
ran

array([0.77158325, 0.11108673, 0.65546282, 0.01991779])

In [13]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

**2D Arrays**

In [14]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
z1=np.zeros([5,5])
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
o1=np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
I=np.eye(5)

In [19]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
r1=np.random.rand(4,5)
r1

array([[0.57025106, 0.94058897, 0.32377309, 0.66381934, 0.81682105],
       [0.852402  , 0.6072865 , 0.94923214, 0.69207964, 0.55668721],
       [0.15657823, 0.49632849, 0.2143103 , 0.00120329, 0.03542647],
       [0.61394893, 0.67357198, 0.30864712, 0.55587552, 0.09939081]])

In [21]:
ar
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
print(ar.size)

10


In [27]:
print(ar2.size)

9


In [29]:
print(ar.shape)

(10,)


In [30]:
print(ar2.shape)

(3, 3)


# Operations in Array

**Copy**

**Sort**

**Reshape**

In [31]:
ar3=np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
ar3[2,2]=10

In [33]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [34]:
ar3[1,2]=12
ar3[0,1]=15

In [35]:
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [36]:
ar3=np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [38]:
ar3=np.sort(ar3,axis=0)

In [39]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [40]:
ar3.sum()

65

In [41]:
ar3.sum(axis=0)

array([12, 16, 37])

In [42]:
ar3.sum(axis=1)

array([14, 21, 30])

In [43]:
ar4=np.random.rand(99)
ar4

array([6.04926019e-02, 7.46509279e-01, 6.37402282e-01, 9.47826643e-01,
       2.84805480e-01, 8.03114767e-01, 4.03459830e-01, 6.64394174e-01,
       5.75418471e-01, 5.61630547e-01, 6.27553097e-01, 1.40058275e-01,
       1.18791815e-01, 6.28978854e-01, 5.14224117e-01, 8.66731631e-01,
       2.78533441e-01, 2.38486241e-01, 4.76975766e-01, 5.46476756e-01,
       6.00040253e-01, 1.94672171e-01, 8.33819621e-02, 7.30518375e-01,
       5.36178258e-02, 7.36458430e-01, 8.81244173e-04, 9.15914539e-01,
       9.63864205e-01, 4.28544035e-02, 6.89991144e-01, 6.49825840e-01,
       9.37453621e-01, 2.03422365e-01, 2.92685528e-01, 8.88963768e-01,
       8.97765325e-01, 2.63395491e-01, 1.52360571e-01, 1.13076362e-01,
       7.55612267e-01, 7.71777772e-01, 5.58288112e-02, 7.29682680e-01,
       5.23012815e-01, 2.70826115e-01, 6.21738470e-01, 8.20949743e-01,
       3.69880809e-01, 2.45015587e-01, 6.79636962e-01, 4.36650383e-01,
       7.09943190e-02, 8.14112960e-01, 8.49634808e-01, 7.18205416e-01,
      

In [44]:
ar4.size

99

In [49]:
ar4=ar4.reshape(11,9)

In [50]:
ar4.size

99

In [51]:
ar4.shape

(11, 9)

In [53]:
ar4=ar4a

In [54]:
ar4

array([[6.04926019e-02, 5.61630547e-01, 4.76975766e-01, 9.15914539e-01,
        8.97765325e-01, 2.70826115e-01, 8.49634808e-01, 7.37430364e-01,
        3.75781954e-01, 7.75368597e-01, 3.15526283e-01],
       [7.46509279e-01, 6.27553097e-01, 5.46476756e-01, 9.63864205e-01,
        2.63395491e-01, 6.21738470e-01, 7.18205416e-01, 4.90161422e-01,
        3.26102492e-01, 4.77851747e-01, 5.70630656e-01],
       [6.37402282e-01, 1.40058275e-01, 6.00040253e-01, 4.28544035e-02,
        1.52360571e-01, 8.20949743e-01, 1.21371627e-01, 3.67808665e-01,
        1.73424858e-01, 7.03196843e-01, 2.39232335e-01],
       [9.47826643e-01, 1.18791815e-01, 1.94672171e-01, 6.89991144e-01,
        1.13076362e-01, 3.69880809e-01, 7.49936919e-01, 4.45378734e-01,
        8.25675791e-01, 7.59054471e-01, 8.63960133e-01],
       [2.84805480e-01, 6.28978854e-01, 8.33819621e-02, 6.49825840e-01,
        7.55612267e-01, 2.45015587e-01, 4.70087638e-01, 6.80701947e-01,
        1.01708049e-01, 4.86377438e-01, 1.46200065e-

In [56]:
ar4.shape

(9, 11)

In [57]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [58]:
ar3=ar3.T
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [59]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
ar=np.append(ar,10)

In [63]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
ar=np.delete(ar,6,axis=0)

In [65]:
ar

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10])

In [66]:
ar=np.insert(ar,6,6)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [69]:
ar4=np.concatenate((ar2,ar3),axis=0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [70]:
ar5=np.concatenate((ar2,ar3),axis=1)
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [71]:
np.split(ar4,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [72]:
ar6=np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [76]:
ar6[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
ar6[1]

array([[7, 8, 9],
       [1, 4, 7]])

In [75]:
ar6[2]

array([[ 3,  5,  8],
       [10, 12, 15]])

In [81]:
ar6[0][0][0]

1

# Scalar Expressions

add

subtract

multiply

divide

power

In [82]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [83]:
np.add(ar5,1)

array([[ 2,  3,  4,  2,  5,  8],
       [ 5,  6,  7,  4,  6,  9],
       [ 8,  9, 10, 11, 13, 16]])

# Vector Operations

In [84]:
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [85]:
ar7 = np.add(ar6[0],ar6[1])
ar7

array([[ 8, 10, 12],
       [ 5,  9, 13]])

In [86]:
ar8 = np.multiply(ar6[0],ar6[1])
ar8

array([[ 7, 16, 27],
       [ 4, 20, 42]])

In [87]:
ar9 = np.divide(ar6[0],ar6[1])
ar9

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.25      , 0.85714286]])

In [88]:
np.ceil(ar9)

array([[1., 1., 1.],
       [4., 2., 1.]])

In [89]:
np.floor(ar9)

array([[0., 0., 0.],
       [4., 1., 0.]])

In [90]:
np.round(ar9)

array([[0., 0., 0.],
       [4., 1., 1.]])

# Statistics

In [91]:
np.mean(ar5)

6.111111111111111

In [92]:
np.mean(ar5,axis=0)

array([ 4.        ,  5.        ,  6.        ,  4.66666667,  7.        ,
       10.        ])

In [93]:
np.mean(ar5,axis=1)

array([ 3.        ,  5.16666667, 10.16666667])

In [94]:
np.median(ar5)

5.5

In [95]:
np.median(ar5,axis=1)

array([2.5, 5. , 9.5])

In [96]:
np.min(ar5)

1

In [97]:
np.min(ar5,axis=0)

array([1, 2, 3, 1, 4, 7])

In [98]:
np.max(ar5,axis=0)

array([ 7,  8,  9, 10, 12, 15])

In [103]:
ar10=np.array([2,5,3,8,0,4,1,6,9])

In [104]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [105]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [106]:
np.argmax(ar10)

8

In [107]:
np.argmin(ar10)

4

In [108]:
np.argsort(ar10)

array([4, 6, 0, 2, 5, 1, 7, 3, 8], dtype=int64)

In [109]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [110]:
np.sin(ar10)

array([ 0.90929743, -0.95892427,  0.14112001,  0.98935825,  0.        ,
       -0.7568025 ,  0.84147098, -0.2794155 ,  0.41211849])

In [111]:
np.log(ar10)

C:\Users\black\AppData\Local\Temp\ipykernel_8124\168028880.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar10)


array([0.69314718, 1.60943791, 1.09861229, 2.07944154,       -inf,
       1.38629436, 0.        , 1.79175947, 2.19722458])